[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "D213", "FIX002", "TD003"]

[tool.ruff.lint.per-file-ignores]
"setup.py" = ["D100"]
"models/inference.py" = ["PLR0913"]

[lint.pydocstyle]
convention = "google"
